// TODO refactor and move in config file
export const MenuPermissionMap = {
  games: ['admin'],
  machines: ['admin'],
  'teleport-vr': ['admin'],
  settings: ['admin'],
  permissions: ['admin'],
  cashbox: ['admin'],
  'cashbox-machines': ['admin'],
  gates: ['admin'],
  gate: ['admin'],
  zones: ['admin']
  // 'cashbox/:id': null,
  // billing: null,
  // 'games-tariffs': null,
  // 'income-tariffs': null,
  // transactions: null,
  // amusements: null,
  // hardware: null,
  // 'hardware/:id': null,
  // dashboard: null,
  // 'gates/:id': null,
  // games: null,
  // users: null,
  // 'users/:id': null,
  // 'staff/:id': null,
  // staff: null,
  // groups: null,
  // keychain: null,
  // cards: null,
  // 'user-management': null
};
