export const MenuPermissionMap = {
  dashboard: [],
  administration: ['admin'],
  permissions: ['admin'],
  billing: [],
  'games-tariffs': [],
  'income-tariffs': [],
  transactions: [],
  amusements: [],
  hardware: [],
  users: [],
  'users/:id': [],
  'staff/:id': [],
  staff: ['admin'],
  groups: ['admin'],
  keychain: [],
  cards: [],
  'user-management': [],
  games: [],
  '': []
};
