version: '3.3'

services: # list of services composing your application
   db: # 
     image: microsoft/mssql-server-linux:latest # the image and tag docker will pull from docker hub
     ports:
       - "1433:1433"
     volumes: # this section allows you to configure persistence within multiple restarts
       - db_data:/var/opt/mssql
     restart: always # if the db crash somehow, restart it
     environment: # env variables, you usually set this to override existing ones
       ACCEPT_EULA: Y
       SA_PASSWORD: lhk4p8d8zw1ruDd1
   control_panel: # you application service
     links: [ "db" ]
     ports:
       - "80:80"
       - "443:443"
     environment:
        ASPNETCORE_URLS: http://+:80
     build: ./ # this tells docker-compose to not pull from docker hub, but to build from the Dockerfile it will find in ./
     restart: always
     depends_on: # set a dependency between your service and the database: this means that your application will not run if the db service is not running, but it doesn't assure you that the database will be ready to accept incoming connection (so your application could crash untill the db initializes itself)
       - db
volumes:
    db_data: # this tells docker-compose to save your data in a generic docker volume. You can see existing volumes typing 'docker volume ls'
