export const PropertyMap = {
  index: 'INDEX',
  userName: 'USER_NAME',
  nickName: 'NICK_NAME',
  phone: 'PHONE',
  statuses: 'USER_STATUSES',
  age: 'USER_AGE',
  email: 'EMAIL',
  registered: 'REGISTERED',
  staffGroupName: 'GROUP',
  name: 'NAME',
  permissions: 'GROUP_PERMISSIONS',
  currentOwner: 'CARD_OWNER_LABEL',
  inventoryNumber: 'CARD_INVENTORY_NUMBER',
  enabled: 'CARD_STATE',
  action: 'CARD_CHANGE_STATE',
  number: 'TRANSACTION_NUMBER',
  date: 'TRANSACTION_DATE',
  document: 'TRANSACTION_DOCUMENT',
  operation: 'TRANSACTION_OPERATION',
  invoiceNumber: 'TRANSACTION_INVOICE_NUMBER',
  currency: 'TRANSACTION_CURRENCY',
  amount: 'TRANSACTION_AMOUNT',
  correspondent: 'TRANSACTION_CORRESPONDENT',
  signature: 'TRANSACTION_SIGNATURE',
  dateOfBirth: 'USER_DATE_OF_BIRTH_DAY',
  gender: 'USER_GENDER_LABEL'
};
